version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nasa-api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - NASA_API_KEY=${NASA_API_KEY:-DEMO_KEY}
      - CORS_ORIGIN=http://localhost:3000
      - CACHE_TTL=300000
      - RATE_LIMIT_WINDOW=900000
      - RATE_LIMIT_MAX=100
    volumes:
      - ./backend/src:/app/src:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nasa-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nasa-frontend
    ports:
      - "3000:8080"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api
      - VITE_APP_NAME=NASA Mission Control Dashboard
      - VITE_APP_VERSION=1.0.0
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nasa-network

  # Redis cache (optional, for enhanced caching)
  redis:
    image: redis:7-alpine
    container_name: nasa-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nasa-network

networks:
  nasa-network:
    driver: bridge
    name: nasa-mission-control

volumes:
  redis-data:
    driver: local
    name: nasa-redis-data

# Development override
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
---
# docker-compose.dev.yml content would go here for development overrides